AllCops:
  TargetRubyVersion: 2.1

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Naming/VariableNumber:
  EnforcedStyle: snake_case

# Non-specific exception handling is fine
Style/RescueStandardError:
  EnforcedStyle: 'implicit'

# This would result in too much intermixing of regular and percent arrays, depending on
# context, and makes nested arrays look weird
Style/WordArray:
  Enabled: false

# Helps with readability
Layout/EmptyLines:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

# Helps with readability
Layout/CaseIndentation:
  Enabled: false

# The test code is safe to evaluate
Security/Eval:
  Exclude:
    - 'testing/**/*'

Metrics/BlockLength:
  Exclude:
    # RSpec tests are inherently large blocks of code
    - 'testing/rspec/spec/**/*_spec.rb'
    # Gemspecs are inherently one large block of code
    - cuke_linter.gemspec

# Whitespace improves readability
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# TODO: Figure out why this is
Layout/EndOfLine:
  Exclude:
    # Git isn't changing the line endings locally for some reason
    - 'bin/console'
