# rubocop:disable Layout/LineLength
ENV['MOST_CURRENT_CUKE_MODELER_VERSION'] ||= '3'

ENV['CUKE_LINTER_PARALLEL_RUN'] ||= 'false'
ENV['CUKE_LINTER_REPORT_FOLDER'] ||= "#{__dir__}/reports"

ENV['CUKE_LINTER_RSPEC_REPORT_NAME'] ||= 'rspec_report'
ENV['CUKE_LINTER_RSPEC_REPORT_HTML_FILE'] ||= "#{ENV.fetch('CUKE_LINTER_RSPEC_REPORT_NAME')}.html"
ENV['CUKE_LINTER_RSPEC_REPORT_HTML_FILE_PATH'] ||= "#{ENV.fetch('CUKE_LINTER_REPORT_FOLDER')}/#{ENV.fetch('CUKE_LINTER_RSPEC_REPORT_HTML_FILE')}"
ENV['CUKE_LINTER_RSPEC_REPORT_JSON_FILE'] ||= "#{ENV.fetch('CUKE_LINTER_RSPEC_REPORT_NAME')}.json"
ENV['CUKE_LINTER_RSPEC_REPORT_JSON_FILE_PATH'] ||= "#{ENV.fetch('CUKE_LINTER_REPORT_FOLDER')}/#{ENV.fetch('CUKE_LINTER_RSPEC_REPORT_JSON_FILE')}"

ENV['CUKE_LINTER_CUCUMBER_REPORT_NAME'] ||= 'cucumber_report'
ENV['CUKE_LINTER_CUCUMBER_REPORT_HTML_FILE'] ||= "#{ENV.fetch('CUKE_LINTER_CUCUMBER_REPORT_NAME')}.html"
ENV['CUKE_LINTER_CUCUMBER_REPORT_HTML_FILE_PATH'] ||= "#{ENV.fetch('CUKE_LINTER_REPORT_FOLDER')}/#{ENV.fetch('CUKE_LINTER_CUCUMBER_REPORT_HTML_FILE')}"
ENV['CUKE_LINTER_CUCUMBER_REPORT_JSON_FILE'] ||= "#{ENV.fetch('CUKE_LINTER_CUCUMBER_REPORT_NAME')}.json"
ENV['CUKE_LINTER_CUCUMBER_REPORT_JSON_FILE_PATH'] ||= "#{ENV.fetch('CUKE_LINTER_REPORT_FOLDER')}/#{ENV.fetch('CUKE_LINTER_CUCUMBER_REPORT_JSON_FILE')}"
# rubocop:enable Layout/LineLength
