#!/usr/bin/env ruby

require "cuke_linter"
require 'optparse'

params         = {}
params[:paths] = []

parser = OptionParser.new do |options|

  options.set_summary_width(20)

  options.on('-p', '--path PATH', String,
             'The file path that should be linted. Can be a file or directory.',
             'This option can be specified multiple times in order to lint',
             'multiple, unconnected locations.') do |path|
    params[:paths] << path
  end

  options.on('-h', '--help', 'Display the help that you are reading now.') do
    puts options.help
    exit
  end

  options.on('-v', '--version', 'Display the version of the gem being used.') do
    puts CukeLinter::VERSION
    exit
  end

end

begin
  parser.parse!
rescue OptionParser::InvalidOption, OptionParser::MissingArgument => e
  puts e.message
  puts parser.help

  exit(1)
end

file_paths = params[:paths]

options              = {}
options[:file_paths] = file_paths

CukeLinter.lint(options)
